messages:
  helpMessage:
    togglevanish: "§eVanish status: {status}"
    togglestaffchat: "§bStaff Chat status: {status}"
  actionBarFormat: "§eVanished: {vanish} §7| §bStaff Chat: {staffchat}"
  staffChatFormat: "§b[StaffChat] §7{prefix}{player} §f>> §e{message}"
  noPermission: "§c{prefix} You don't have permission!"
  prefix: "§e[Pixel Burma]"
  chatMuted: "Chat is currently muted!"
  chatCleared: "Chat has been cleared!"
  chatToggle: "Chat has been {status}!"
  status:
    muted: "§cmuted"
    unmuted: "§aunmuted"
