name: StaffFeatures
version: 1.0
main: com.thomas.staff.StaffFeaturesPlugin
api-version: 1.20
author: Thomas
description: Staff utilities with action bar status

commands:
  togglevanish:
    description: Toggle vanish status
    permission: stafffeatures.toggle.vanish
  togglestaffchat:
    description: Toggle staff chat status
    permission: stafffeatures.toggle.staffchat
  togglefeature:
    description: Toggle feature status
    permission: stafffeatures.toggle.feature

permissions:
  stafffeatures.use:
    description: See the staff action bar
    default: op
  stafffeatures.toggle.vanish:
    description: Toggle vanish
    default: op
  stafffeatures.toggle.staffchat:
    description: Toggle staff chat
    default: op
  stafffeatures.toggle.feature:
    description: Toggle the feature
    default: op
