name: StaffFeatures
version: 1.0
main: com.thomas.staff.StaffFeaturesPlugin
api-version: 1.20
author: Thomas
description: Staff utilities with action bar + staff chat

commands:
  togglevanish:
    description: Toggle vanish status
    permission: stafffeatures.toggle.vanish
  togglestaffchat:
    description: Toggle staff chat status
    permission: stafffeatures.toggle.staffchat

permissions:
  stafffeatures.use:
    description: See the staff action bar
    default: op
  stafffeatures.toggle.vanish:
    description: Toggle vanish
    default: op
  stafffeatures.toggle.staffchat:
    description: Toggle staff chat
    default: op
  stafffeatures.staffchat:
    description: Send and receive staff chat
    default: op
