messages:
  helpMessage:
    togglevanish: "§eVanish status: {status}"
    togglestaffchat: "§bStaff Chat status: {status}"
    togglefeature: "§aFeature status: {status}"
  actionBarFormat: "§eVanished: {vanish} §7| §bStaff Chat: {staffchat} §7| §aFeature: {feature}"
