name: StaffFeatures
version: 1.0
main: com.thomas.staff.StaffFeaturesPlugin
api-version: 1.20
author: Thomas
description: Staff utilities with action bar status
permissions:
  stafffeatures.use:
    description: Allows player to see staff features action bar
    default: op
